import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import prisma from "../lib/prisma.js";
import puppeteer from "puppeteer";
import * as Sentry from "@sentry/node";

export const reportsRouter = Router();

reportsRouter.get("/monthly", requireAuth, async (req, res) => {
  try {
    const month = req.query.month;
    if (!month || !/^\d{4}-\d{2}$/.test(month)) {
      return res.status(400).json({ error: "Query month=YYYY-MM required" });
    }
    const [y, m] = month.split("-").map(Number);
    const start = new Date(y, m - 1, 1);
    const end = new Date(y, m, 0, 23, 59, 59, 999);

    const dealer = await prisma.dealer.findUnique({
      where: { id: req.dealer.id },
      select: { dealershipName: true, name: true },
    });
    if (!dealer) return res.status(404).json({ error: "Dealer not found" });

    const leads = await prisma.lead.findMany({
      where: { dealerId: req.dealer.id, createdAt: { gte: start, lte: end } },
      include: { car: true },
    });
    const testDrives = await prisma.testDrive.findMany({
      where: { dealerId: req.dealer.id, date: { gte: start, lte: end } },
      include: { car: true },
    });
    const closed = leads.filter((l) => l.status === "CLOSED");
    const revenueClosed = closed.reduce((s, l) => s + (l.car?.price || 0), 0);
    const notContacted = leads.filter((l) => l.status === "NEW").length;
    const avgPrice = leads.length ? leads.reduce((s, l) => s + (l.car?.price || 0), 0) / leads.length : 0;
    const estimatedLost = Math.round(notContacted * avgPrice * 0.1);

    const carLeadCount = {};
    leads.forEach((l) => {
      const key = l.carId;
      if (!carLeadCount[key]) carLeadCount[key] = { car: l.car, count: 0 };
      carLeadCount[key].count++;
    });
    const topCars = Object.values(carLeadCount).sort((a, b) => b.count - a.count).slice(0, 5);

    const byStatus = {};
    leads.forEach((l) => {
      byStatus[l.status] = (byStatus[l.status] || 0) + 1;
    });

    const monthLabel = start.toLocaleString("default", { month: "long", year: "numeric" });

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: system-ui, sans-serif; padding: 24px; color: #1a1a1a; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .sub { color: #666; font-size: 14px; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    th { background: #f5f5f5; }
    .section { margin: 24px 0; }
    .section h2 { font-size: 16px; margin-bottom: 8px; }
    .footer { margin-top: 32px; font-size: 12px; color: #888; }
  </style>
</head>
<body>
  <h1>MotorIQ</h1>
  <p class="sub">${dealer.dealershipName} — ${monthLabel}</p>

  <div class="section">
    <h2>Summary</h2>
    <p><strong>Total Leads:</strong> ${leads.length}</p>
    <p><strong>Hot Leads (Contacted/Test Drive/Negotiation):</strong> ${leads.filter((l) => ["CONTACTED", "TEST_DRIVE", "NEGOTIATION"].includes(l.status)).length}</p>
    <p><strong>Test Drives:</strong> ${testDrives.length}</p>
    <p><strong>Closed Deals:</strong> ${closed.length}</p>
    <p><strong>Revenue Closed:</strong> KES ${revenueClosed.toLocaleString()}</p>
  </div>

  <div class="section">
    <h2>Sales Leakage</h2>
    <p>Estimated revenue lost (leads not contacted × avg car price × 10%): <strong>KES ${estimatedLost.toLocaleString()}</strong></p>
  </div>

  <div class="section">
    <h2>Top 5 cars by leads</h2>
    <table>
      <tr><th>Car</th><th>Leads</th></tr>
      ${topCars.map(({ car, count }) => `<tr><td>${car?.make || ""} ${car?.model || ""} (${car?.year || ""})</td><td>${count}</td></tr>`).join("")}
    </table>
  </div>

  <div class="section">
    <h2>Lead status breakdown</h2>
    <table>
      <tr><th>Status</th><th>Count</th></tr>
      ${Object.entries(byStatus).map(([k, v]) => `<tr><td>${k.replace("_", " ")}</td><td>${v}</td></tr>`).join("")}
    </table>
  </div>

  <p class="footer">Generated by MotorIQ — motoriq.co.ke</p>
</body>
</html>
    `;

    const browser = await puppeteer.launch({ headless: true, args: ["--no-sandbox"] });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });
    const pdf = await page.pdf({ format: "A4" });
    await browser.close();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="motoriq-report-${month}.pdf"`);
    res.send(pdf);
  } catch (e) {
    console.error(e);
    if (process.env.SENTRY_DSN) {
      Sentry.captureException(e);
    }
    res.status(500).json({ error: "Failed to generate report" });
  }
});

/** Escape a CSV cell (quotes and commas) */
function csvEscape(val) {
  if (val == null || val === "") return "";
  const s = String(val);
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return '"' + s.replace(/"/g, '""') + '"';
  }
  return s;
}

/** GET /api/reports/analytics-csv?month=YYYY-MM — export leads as CSV (optional month filter) */
reportsRouter.get("/analytics-csv", requireAuth, async (req, res) => {
  try {
    const month = req.query.month;
    const where = { dealerId: req.dealer.id };
    if (month && /^\d{4}-\d{2}$/.test(month)) {
      const [y, m] = month.split("-").map(Number);
      where.createdAt = {
        gte: new Date(y, m - 1, 1),
        lte: new Date(y, m, 0, 23, 59, 59, 999),
      };
    }

    const leads = await prisma.lead.findMany({
      where,
      include: { car: { select: { make: true, model: true, year: true, price: true } } },
      orderBy: { createdAt: "desc" },
    });

    const headers = [
      "Name",
      "Email",
      "Phone",
      "Status",
      "Source",
      "Score",
      "Budget",
      "Financing",
      "Timeframe",
      "Trade-in",
      "Car",
      "Car Price (KES)",
      "Created",
      "Updated",
      "Notes",
    ];
    const rows = leads.map((l) => [
      csvEscape(l.name),
      csvEscape(l.email),
      csvEscape(l.phone),
      csvEscape(l.status),
      csvEscape(l.source),
      csvEscape(l.score),
      csvEscape(l.budget),
      csvEscape(l.financing),
      csvEscape(l.timeframe),
      csvEscape(l.tradeIn),
      csvEscape(l.car ? `${l.car.make} ${l.car.model} (${l.car.year})` : ""),
      csvEscape(l.car?.price != null ? l.car.price : ""),
      csvEscape(l.createdAt ? new Date(l.createdAt).toISOString() : ""),
      csvEscape(l.updatedAt ? new Date(l.updatedAt).toISOString() : ""),
      csvEscape(l.notes),
    ]);

    const csv = [headers.join(","), ...rows.map((r) => r.join(","))].join("\n");
    const filename = month
      ? `motoriq-analytics-${month}.csv`
      : `motoriq-analytics-${new Date().toISOString().slice(0, 10)}.csv`;

    res.setHeader("Content-Type", "text/csv; charset=utf-8");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.send("\uFEFF" + csv); // BOM for Excel UTF-8
  } catch (e) {
    console.error(e);
    res.status(500).json({ error: "Failed to export CSV" });
  }
});
