-- Ensure Affiliate has all columns expected by Prisma schema (idempotent)
ALTER TABLE "Affiliate" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Affiliate" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Affiliate" ADD COLUMN IF NOT EXISTS "commissionRate" DECIMAL(10,4);
ALTER TABLE "Affiliate" ADD COLUMN IF NOT EXISTS "payoutRate" DECIMAL(10,4);
ALTER TABLE "Affiliate" ADD COLUMN IF NOT EXISTS "totalEarned" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Affiliate" ADD COLUMN IF NOT EXISTS "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Affiliate" ADD COLUMN IF NOT EXISTS "lastPayoutAt" TIMESTAMP(3);
